### PR TITLE
Added setup.py, setup.cfg and pyproject.toml.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by djc** [comment]
Hi, thanks for your contribution! I'll admit to not being entirely up to date with how Python packaging functions in 2021, but can you please explain why adding these files would be useful/why these would help?

**Comment by KOLANICH** [comment]
>can you please explain why adding these files would be useful/why these would help?

`setup.py` - needed in order to use `setuptools_rust`, since it seems it doesn't support the declarative config.
`setup.cfg` - package metadata lives here since 2016. Before 2016 it had to be in `setup.py`.
`pyproject.toml` - needed for PEP 517 compliance, also metadata from `setup.cfg` should be moved there (and `setup.cfg` deleted) when `setuptools` have PEP 621 implemented.

**Comment by djc** [comment]
So far I've used maturin to build this project. It has build, develop and publish commands. This seems like a simpler and potentially more modern solution, especially compared to setuptools_rust. I think having the `pyproject.toml` could still make sense, though I'd prefer to duplicate as little information as possible between `Cargo.toml` and `pyproject.toml`.

**Comment by KOLANICH** [comment]
>I think having the pyproject.toml could still make sense, though I'd prefer to duplicate as little information as possible between Cargo.toml and pyproject.toml.

I completely aggree with that, I have the same though. But IMHO pulling data from `cargo.toml` should be implemented within `setuptools_rust` itself.

>I've used maturin to build this project. It has build, develop and publish commands. This seems like a simpler

I cannot call it simpler, because
* `maturin` has to be built itself. And itis written in rust itself. So all kinds of issues.
* if I understand right, it is not a PEP 517-compliant solution, so `python3 -m build -w` won't build a wheel. I heavily rely on PEP 517-compliance in my CI pipelines, since it makes scripts much easier - instead of detecting the type of a project heuristically and using build tools in specific ways each one, I just use `python3 -m build`

BTW, why using a cext instead of a pure-python module + `ctypes` + a shared library? `ctypes`-based solutions are much more compatible with impls other than cpython and portable and robust (I mean, there is no need to recompile extension for each python version, python just updates and everything just works out of the box)?

**Comment by djc** [comment]
> I cannot call it simpler, because
>
> * maturin has to be built itself (I couldn't have built it, it looks like that in order to have maturin one has to have an already working maturin, ahd I don't trust the binary builds provided by someone in the Internet). And it is written in rust itself. So all kinds of issues.

"all kinds of issues" seems like an exaggeration. You can trivially build maturin from source by call `cargo install maturin`. It is written in Rust itself, but that doesn't seem like an issue if you're trying to compile a Rust project anyway.

> * if I understand right, it is not a PEP 517-compliant solution, so python3 -m build -w won't build a wheel. I heavily rely on PEP 517-compliance in my CI pipelines, since it makes scripts much easier - instead of detecting the type of a project heuristically and using build tools in specific ways each one, I just use python3 -m build

Can you unpack for me what the exact CLI commands should look like? I looked at PEP 517 but it's not obvious to me how this is supposed to work. In particular, where does the `build` part of `python3 -m build -w` come from? I am sensitive to the argument that our build process should fit in with what Python developers are accustomed to.

> BTW, why using a cext instead of a pure-python module + ctypes + a shared library? ctypes-based solutions are much more compatible with impls other than cpython and portable and robust (I mean, there is no need to recompile extension for each python version, python just updates and everything just works out of the box)?

What other Python impls are you interested in? I'm not sure what you mean by `cext`; for now I am just using maturin's default settings. It seems to me like cffi would be better for PyPy than C extensions. Rust libraries don't have a stable ABI, so I doubt that ctypes + a shared library would easily get you a library that works across Python versions and also across Rust versions.

**Comment by KOLANICH** [comment]
>You can trivially build maturin from source by call cargo install maturin.

>You can trivially build maturin from source by call cargo install maturin. 

Thanks, that looks better, at least building process has started (it haven't built though, because rustc package in Ubuntu doesn't have `str_split_once` stabilized because the packages in distros are kinda old (for Rust tempo) ). `pyproject.toml` in the root has suggested that I should build it with `build` rather than with `cargo`. 

>In particular, where does the build part of python3 -m build -w come from?

From here: https://github.com/pypa/build . It is a pypa-blessed PEP 517 build CLI frontend.

>What other Python impls are you interested in?

JITed ones: pypy and graalpython. And maybe iron python, if it uses .net jit under hood.

>I'm not sure what you mean by cext;

Python extensions written not in python itself and interacting with cpython internals.

>It seems to me like cffi would be better for PyPy than C extensions.

If I rememeber right,  cffi requires a compiler. To be honest, I don't understand why people use cffi, I don't see the benefits. BTW there also exist generators of code using ctypes from C header files, but I usually use them only once, then the generated code is edited manually.

>Rust libraries don't have a stable ABI, so I doubt that ctypes + a shared library would easily get you a library that works across Python versions and also across Rust versions.

Ooops. Thanks for the info.

**Comment by djc** [comment]
It seems like adding a minimal `pyproject.toml` is sufficient to make `build` work:

```toml
[build-system]
requires = ["maturin >= 0.11, < 0.12"]
build-backend = "maturin"
```

```
djc-2019 main instant-distance-py $ python3 -m build -w
* Creating venv isolated environment...
* Installing packages in isolated environment... (maturin >= 0.11, < 0.12)
* Getting dependencies for wheel...
* Building wheel...
Running `maturin pep517 build-wheel -i /private/var/folders/wl/fgp_zytx50v_4hm8k0y14hc00000gn/T/build-env-c_c8bwbv/bin/python`
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.28
   Compiling unicode-xid v0.2.2
   Compiling libc v0.2.98
   Compiling syn v1.0.74
   Compiling crossbeam-utils v0.8.5
   Compiling scopeguard v1.1.0
   Compiling pyo3-build-config v0.14.1
   Compiling proc-macro-hack v0.5.19
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.8.0
   Compiling serde_derive v1.0.126
   Compiling crossbeam-epoch v0.9.5
   Compiling serde v1.0.126
   Compiling rayon-core v1.9.1
   Compiling smallvec v1.6.1
   Compiling unindent v0.1.7
   Compiling ppv-lite86 v0.2.10
   Compiling either v1.6.1
   Compiling instant v0.1.10
   Compiling lock_api v0.4.4
   Compiling memoffset v0.6.4
   Compiling num-traits v0.2.14
   Compiling rayon v1.5.1
   Compiling crossbeam-channel v0.5.1
   Compiling pyo3 v0.14.1
   Compiling paste-impl v0.1.18
   Compiling quote v1.0.9
   Compiling getrandom v0.2.3
   Compiling parking_lot_core v0.8.3
   Compiling num_cpus v1.13.0
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.11.1
   Compiling rand_chacha v0.3.1
   Compiling crossbeam-deque v0.8.0
   Compiling paste v0.1.18
   Compiling rand v0.8.4
   Compiling ordered-float v2.7.0
   Compiling pyo3-macros-backend v0.14.1
   Compiling indoc-impl v0.3.6
   Compiling indoc v0.3.6
   Compiling pyo3-macros v0.14.1
   Compiling serde-big-array v0.3.2
   Compiling bincode v1.3.3
   Compiling instant-distance v0.5.0 (/Users/djc/src/instant-distance/instant-distance)
   Compiling instant-distance-py v0.3.1 (/Users/djc/src/instant-distance/instant-distance-py)
    Finished release [optimized] target(s) in 17.86s
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at /private/var/folders/wl/fgp_zytx50v_4hm8k0y14hc00000gn/T/build-env-c_c8bwbv/bin/python
📦 Built wheel for CPython 3.9 to /Users/djc/src/instant-distance/target/wheels/instant_distance-0.3.1-cp39-cp39-macosx_10_7_x86_64.whl
/Users/djc/src/instant-distance/target/wheels/instant_distance-0.3.1-cp39-cp39-macosx_10_7_x86_64.whl
Successfully built instant_distance-0.3.1-cp39-cp39-macosx_10_7_x86_64.whl
```

**Comment by KOLANICH** [comment]
Nice to know that maturin is PEP 517-compatible. Though it doesn't resolve other issues around `maturin`. I'd close this PR for now, may reopen in future.

**Comment by djc** [comment]
IIRC cffi was developed by the Pypy folks exactly because it enabled portability across CPython and Pypy. I don't know much about how it works, though. In any case, maturin does seem to have some Pypy support, as well.

What version of Rust are you getting from Ubuntu these days?

What other issues with maturin do you mean? If we could get it to build on older Rust compilers, would that be sufficient?

**Comment by KOLANICH** [comment]
>What version of Rust are you getting from Ubuntu these days?

1.51

<details>
<summary>Repology</summary>


</summary>

Though I have managed to build it after reverting 1 commit and adding a small change into source.

But what especially worries me is its large amount of dependencies and large size and quite large build time. I'd still prefer `setuptools_rust`.

**Pull request closed without merging**
